### ISSUE TITLE
No resolver working

### ISSUE THREAD

**Issue by Nabla128k** [jackyNIX/xbmc-mixcloud-plugin#7]
Hi,
it seems that something has changed and currently no resolver is working.
LOG:

20:31:17.535 T:1651503872  NOTICE: MIXCLOUD ##########################################################
20:31:17.535 T:1651503872  NOTICE: MIXCLOUD Mode: 40
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD Offset: 0
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD Key: /feelmybicep/fmb-mixtape-92-lake-people/
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD Query:
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD ##########################################################
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD Resolverid _curr=0 _orig=0
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD Resolving mixcloud-downloader cloudcast stream for http://www.mixcloud.com/feelmybicep/fmb-mixtape-92-lake-people/
20:31:17.536 T:1651503872  NOTICE: MIXCLOUD Link version 2
20:31:23.721 T:1651503872  NOTICE: MIXCLOUD Unable to resolve
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Cannot solve using current resolver
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Changing resolver to 1
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Locally resolving cloudcast stream for http://www.mixcloud.com/feelmybicep/fmb-mixtape-92-lake-people/
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Changing resolver to 2
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Resolving offliberty cloudcast stream for http://www.mixcloud.com/feelmybicep/fmb-mixtape-92-lake-people/
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Changing resolver to 3
20:31:23.722 T:1651503872  NOTICE: MIXCLOUD Resolving m4a cloudcast stream for http://www.mixcloud.com/feelmybicep/fmb-mixtape-92-lake-people/
20:31:23.723 T:1651503872  NOTICE: MIXCLOUD Changing resolver to 4
20:31:23.723 T:1651503872  NOTICE: MIXCLOUD Resolving mixcloud-downloader cloudcast stream for http://www.mixcloud.com/feelmybicep/fmb-mixtape-92-lake-people/
20:31:23.723 T:1651503872  NOTICE: MIXCLOUD Link version 1
20:31:24.839 T:1651503872  NOTICE: MIXCLOUD Unable to resolve
20:31:24.840 T:1651503872  NOTICE: MIXCLOUD Changing resolver to 5
20:31:24.840 T:1651503872  NOTICE: MIXCLOUD Resolving mixcloud-downloader cloudcast stream for http://www.mixcloud.com/feelmybicep/fmb-mixtape-92-lake-people/
20:31:24.840 T:1651503872  NOTICE: MIXCLOUD Link version 2
20:31:25.967 T:1651503872  NOTICE: MIXCLOUD Unable to resolve
20:31:25.968 T:1651503872  NOTICE: MIXCLOUD Stop player
20:31:25.969 T:1926048256   ERROR: Playlist Player: skipping unplayable item: 2, path [plugin://plugin.audio.mixcloud/?mode=40&key=%2Ffeelmybicep%2Ffmb-mixtape-92-lake$

Can I do anything?

**Comment by Nabla128k** [comment]
Well, update: it seems, that mixcloud-downloader.com now requires captcha... 
Direct slow stream for example from log is
http://stream9.mixcloud.com/secure/c/m4a/64/1/9/6/4/6400-277a-4e2b-b29b-1654980e73c9.m4a?sig=WOPQhNLDXasgAHcGf_A7Ug

Didn't look into code, if this has somehow changed...

**Comment by Nabla128k** [comment]
Aha, get_stream_m4a() function is not functional, so just mixcloud-downloader.com resolver was working...?

**Comment by jackyNIX** [comment]
take a look at the kodi forum thread...
